services:
  payment-service:
    build: ./payment-service
    ports:
      - "8081:8081"
  inventory-service:
    build: ./inventory-service
    ports:
      - "8082:8082"
  shipping-service:
    build: ./shipping-service
    ports:
      - "8083:8083"
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
